//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGLUONG
    {
        public string MaBL { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> SoNgayLam { get; set; }
        public Nullable<int> SoNgayNghiCoPhep { get; set; }
        public Nullable<int> SoNgayNghiKhongPhep { get; set; }
        public Nullable<decimal> TongPhuCap { get; set; }
        public Nullable<decimal> TongTru { get; set; }
        public Nullable<decimal> TongLuong { get; set; }
        public string MaNV { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
