//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGCHAMCONG
    {
        public string MaCC { get; set; }
        public System.DateTime NgayChamCong { get; set; }
        public Nullable<System.TimeSpan> GioVao { get; set; }
        public Nullable<System.TimeSpan> GioRa { get; set; }
        public string MaNV { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
