//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONXINNGHI
    {
        public string MaDon { get; set; }
        public System.DateTime TuNgay { get; set; }
        public System.DateTime DenNgay { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string MaNV { get; set; }
        public string LyDo { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
