//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLNSEntities : DbContext
    {
        public QLNSEntities()
            : base(UserSession.EFConnectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANGCHAMCONG> BANGCHAMCONGs { get; set; }
        public virtual DbSet<BANGLUONG> BANGLUONGs { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<DONXINNGHI> DONXINNGHIs { get; set; }
        public virtual DbSet<HOPDONG> HOPDONGs { get; set; }
        public virtual DbSet<NHANPHUCAP> NHANPHUCAPs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHONGBAN> PHONGBANs { get; set; }
        public virtual DbSet<PHUCAP> PHUCAPs { get; set; }
    
        public virtual int sp_ThemPhongBan(string tenPB, string diaDiem)
        {
            var tenPBParameter = tenPB != null ?
                new ObjectParameter("TenPB", tenPB) :
                new ObjectParameter("TenPB", typeof(string));
    
            var diaDiemParameter = diaDiem != null ?
                new ObjectParameter("DiaDiem", diaDiem) :
                new ObjectParameter("DiaDiem", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemPhongBan", tenPBParameter, diaDiemParameter);
        }
    
        public virtual int sp_SuaPhongBan(string maPB, string tenPB, string diaDiem)
        {
            var maPBParameter = maPB != null ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(string));
    
            var tenPBParameter = tenPB != null ?
                new ObjectParameter("TenPB", tenPB) :
                new ObjectParameter("TenPB", typeof(string));
    
            var diaDiemParameter = diaDiem != null ?
                new ObjectParameter("DiaDiem", diaDiem) :
                new ObjectParameter("DiaDiem", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaPhongBan", maPBParameter, tenPBParameter, diaDiemParameter);
        }
    
        public virtual int sp_XoaPhongBan(string maPB)
        {
            var maPBParameter = maPB != null ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaPhongBan", maPBParameter);
        }
    
        public virtual int sp_ThemPhuCap(string tenPC, Nullable<decimal> soTien)
        {
            var tenPCParameter = tenPC != null ?
                new ObjectParameter("TenPC", tenPC) :
                new ObjectParameter("TenPC", typeof(string));
    
            var soTienParameter = soTien.HasValue ?
                new ObjectParameter("SoTien", soTien) :
                new ObjectParameter("SoTien", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemPhuCap", tenPCParameter, soTienParameter);
        }
    
        public virtual int sp_SuaPhuCap(string maPC, string tenPC, Nullable<decimal> soTien)
        {
            var maPCParameter = maPC != null ?
                new ObjectParameter("MaPC", maPC) :
                new ObjectParameter("MaPC", typeof(string));
    
            var tenPCParameter = tenPC != null ?
                new ObjectParameter("TenPC", tenPC) :
                new ObjectParameter("TenPC", typeof(string));
    
            var soTienParameter = soTien.HasValue ?
                new ObjectParameter("SoTien", soTien) :
                new ObjectParameter("SoTien", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaPhuCap", maPCParameter, tenPCParameter, soTienParameter);
        }
    
        public virtual int sp_XoaPhuCap(string maPC)
        {
            var maPCParameter = maPC != null ?
                new ObjectParameter("MaPC", maPC) :
                new ObjectParameter("MaPC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaPhuCap", maPCParameter);
        }
    
        public virtual int sp_ThemNhanVien(string hoTen, Nullable<System.DateTime> ngaySinh, string gioiTinh, string diaChi, string sdt, string email, string tenCV, string tenPB)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("Sdt", sdt) :
                new ObjectParameter("Sdt", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var tenCVParameter = tenCV != null ?
                new ObjectParameter("TenCV", tenCV) :
                new ObjectParameter("TenCV", typeof(string));
    
            var tenPBParameter = tenPB != null ?
                new ObjectParameter("TenPB", tenPB) :
                new ObjectParameter("TenPB", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNhanVien", hoTenParameter, ngaySinhParameter, gioiTinhParameter, diaChiParameter, sdtParameter, emailParameter, tenCVParameter, tenPBParameter);
        }
    
        public virtual int sp_SuaNhanVien(string maNV, string hoTen, Nullable<System.DateTime> ngaySinh, string gioiTinh, string diaChi, string sdt, string email, string tenCV, string tenPB)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("Sdt", sdt) :
                new ObjectParameter("Sdt", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var tenCVParameter = tenCV != null ?
                new ObjectParameter("TenCV", tenCV) :
                new ObjectParameter("TenCV", typeof(string));
    
            var tenPBParameter = tenPB != null ?
                new ObjectParameter("TenPB", tenPB) :
                new ObjectParameter("TenPB", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaNhanVien", maNVParameter, hoTenParameter, ngaySinhParameter, gioiTinhParameter, diaChiParameter, sdtParameter, emailParameter, tenCVParameter, tenPBParameter);
        }
    
        public virtual int sp_ChoNghiViec(string maNV)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChoNghiViec", maNVParameter);
        }
    
        public virtual int sp_ThemHopDong(Nullable<System.DateTime> ngayBD, Nullable<System.DateTime> ngayKT, Nullable<System.DateTime> ngayKy, Nullable<decimal> mucLuong, string maNV)
        {
            var ngayBDParameter = ngayBD.HasValue ?
                new ObjectParameter("NgayBD", ngayBD) :
                new ObjectParameter("NgayBD", typeof(System.DateTime));
    
            var ngayKTParameter = ngayKT.HasValue ?
                new ObjectParameter("NgayKT", ngayKT) :
                new ObjectParameter("NgayKT", typeof(System.DateTime));
    
            var ngayKyParameter = ngayKy.HasValue ?
                new ObjectParameter("NgayKy", ngayKy) :
                new ObjectParameter("NgayKy", typeof(System.DateTime));
    
            var mucLuongParameter = mucLuong.HasValue ?
                new ObjectParameter("MucLuong", mucLuong) :
                new ObjectParameter("MucLuong", typeof(decimal));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemHopDong", ngayBDParameter, ngayKTParameter, ngayKyParameter, mucLuongParameter, maNVParameter);
        }
    
        public virtual int sp_SuaHopDong(string maHD, Nullable<System.DateTime> ngayBD, Nullable<System.DateTime> ngayKT, Nullable<System.DateTime> ngayKy, Nullable<decimal> mucLuong, string maNV)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            var ngayBDParameter = ngayBD.HasValue ?
                new ObjectParameter("NgayBD", ngayBD) :
                new ObjectParameter("NgayBD", typeof(System.DateTime));
    
            var ngayKTParameter = ngayKT.HasValue ?
                new ObjectParameter("NgayKT", ngayKT) :
                new ObjectParameter("NgayKT", typeof(System.DateTime));
    
            var ngayKyParameter = ngayKy.HasValue ?
                new ObjectParameter("NgayKy", ngayKy) :
                new ObjectParameter("NgayKy", typeof(System.DateTime));
    
            var mucLuongParameter = mucLuong.HasValue ?
                new ObjectParameter("MucLuong", mucLuong) :
                new ObjectParameter("MucLuong", typeof(decimal));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaHopDong", maHDParameter, ngayBDParameter, ngayKTParameter, ngayKyParameter, mucLuongParameter, maNVParameter);
        }
    
        public virtual int sp_HuyHopDong(string maHD)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_HuyHopDong", maHDParameter);
        }
    
        public virtual int sp_TuDongCapNhatTrangThaiHD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TuDongCapNhatTrangThaiHD");
        }
    
        public virtual int sp_CapNhatTrangThaiDon(string maDon, Nullable<int> trangThai)
        {
            var maDonParameter = maDon != null ?
                new ObjectParameter("MaDon", maDon) :
                new ObjectParameter("MaDon", typeof(string));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatTrangThaiDon", maDonParameter, trangThaiParameter);
        }
    
        [DbFunction("QLNSEntities", "fn_TinhNgayNghiThang")]
        public virtual IQueryable<fn_TinhNgayNghiThang_Result> fn_TinhNgayNghiThang(string maNV, Nullable<int> thang, Nullable<int> nam, Nullable<int> phepConLai)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            var phepConLaiParameter = phepConLai.HasValue ?
                new ObjectParameter("PhepConLai", phepConLai) :
                new ObjectParameter("PhepConLai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TinhNgayNghiThang_Result>("[QLNSEntities].[fn_TinhNgayNghiThang](@MaNV, @Thang, @Nam, @PhepConLai)", maNVParameter, thangParameter, namParameter, phepConLaiParameter);
        }
    
        public virtual int sp_ChotBangLuongThang(Nullable<int> thang, Nullable<int> nam, Nullable<decimal> congChuan)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            var congChuanParameter = congChuan.HasValue ?
                new ObjectParameter("CongChuan", congChuan) :
                new ObjectParameter("CongChuan", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChotBangLuongThang", thangParameter, namParameter, congChuanParameter);
        }
    
        public virtual int sp_ThemNhanPhuCap(string maNV, string tenPC, string noiDung)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var tenPCParameter = tenPC != null ?
                new ObjectParameter("TenPC", tenPC) :
                new ObjectParameter("TenPC", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNhanPhuCap", maNVParameter, tenPCParameter, noiDungParameter);
        }
    
        public virtual int sp_XoaNhanPhuCap(string maNV, string maPC)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maPCParameter = maPC != null ?
                new ObjectParameter("MaPC", maPC) :
                new ObjectParameter("MaPC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaNhanPhuCap", maNVParameter, maPCParameter);
        }
    
        public virtual int sp_CapNhatThongTinCaNhan(string hoTen, Nullable<System.DateTime> ngaySinh, string gioiTinh, string diaChi, string sdt, string email)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("Sdt", sdt) :
                new ObjectParameter("Sdt", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatThongTinCaNhan", hoTenParameter, ngaySinhParameter, gioiTinhParameter, diaChiParameter, sdtParameter, emailParameter);
        }
    
        public virtual int sp_ThemDonXinNghi(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string lyDo)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var lyDoParameter = lyDo != null ?
                new ObjectParameter("LyDo", lyDo) :
                new ObjectParameter("LyDo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemDonXinNghi", tuNgayParameter, denNgayParameter, lyDoParameter);
        }
    
        public virtual ObjectResult<sp_XemThongTinCaNhan_Result> sp_XemThongTinCaNhan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_XemThongTinCaNhan_Result>("sp_XemThongTinCaNhan");
        }
    
        public virtual ObjectResult<sp_XemLuongThangCaNhan_Result> sp_XemLuongThangCaNhan(Nullable<int> thang, Nullable<int> nam)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_XemLuongThangCaNhan_Result>("sp_XemLuongThangCaNhan", thangParameter, namParameter);
        }
    
        public virtual ObjectResult<sp_XemDonXinNghiCaNhan_Result> sp_XemDonXinNghiCaNhan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_XemDonXinNghiCaNhan_Result>("sp_XemDonXinNghiCaNhan");
        }
    
        public virtual ObjectResult<sp_ThongKeLuongTheoChucVu_Result> sp_ThongKeLuongTheoChucVu(Nullable<int> thang, Nullable<int> nam)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKeLuongTheoChucVu_Result>("sp_ThongKeLuongTheoChucVu", thangParameter, namParameter);
        }
    
        public virtual ObjectResult<sp_ThongKeLuongTheoPhongBan_Result> sp_ThongKeLuongTheoPhongBan(Nullable<int> thang, Nullable<int> nam)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKeLuongTheoPhongBan_Result>("sp_ThongKeLuongTheoPhongBan", thangParameter, namParameter);
        }
    
        public virtual ObjectResult<sp_LayBangLuongTheoThang_Result> sp_LayBangLuongTheoThang(Nullable<int> thang, Nullable<int> nam)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayBangLuongTheoThang_Result>("sp_LayBangLuongTheoThang", thangParameter, namParameter);
        }
    
        public virtual ObjectResult<sp_GetListNhanVien_Result> sp_GetListNhanVien(Nullable<bool> hienThiTatCa, string tuKhoa)
        {
            var hienThiTatCaParameter = hienThiTatCa.HasValue ?
                new ObjectParameter("HienThiTatCa", hienThiTatCa) :
                new ObjectParameter("HienThiTatCa", typeof(bool));
    
            var tuKhoaParameter = tuKhoa != null ?
                new ObjectParameter("TuKhoa", tuKhoa) :
                new ObjectParameter("TuKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetListNhanVien_Result>("sp_GetListNhanVien", hienThiTatCaParameter, tuKhoaParameter);
        }
    
        public virtual ObjectResult<sp_LayDanhSachDon_Result> sp_LayDanhSachDon(Nullable<int> trangThai)
        {
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDanhSachDon_Result>("sp_LayDanhSachDon", trangThaiParameter);
        }
    
        public virtual ObjectResult<sp_GetDanhSachHopDong_Result> sp_GetDanhSachHopDong(string tuKhoa)
        {
            var tuKhoaParameter = tuKhoa != null ?
                new ObjectParameter("TuKhoa", tuKhoa) :
                new ObjectParameter("TuKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetDanhSachHopDong_Result>("sp_GetDanhSachHopDong", tuKhoaParameter);
        }
    
        public virtual ObjectResult<sp_GetListNhanPhuCap_Result> sp_GetListNhanPhuCap()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetListNhanPhuCap_Result>("sp_GetListNhanPhuCap");
        }
    
        public virtual ObjectResult<sp_GetListPhuCap_Result> sp_GetListPhuCap()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetListPhuCap_Result>("sp_GetListPhuCap");
        }
    
        public virtual ObjectResult<sp_GetListPhongBan_Result> sp_GetListPhongBan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetListPhongBan_Result>("sp_GetListPhongBan");
        }
    
        public virtual ObjectResult<sp_GetListChucVu_Result> sp_GetListChucVu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetListChucVu_Result>("sp_GetListChucVu");
        }
    
        public virtual int sp_ThemChucVu(string tenCV)
        {
            var tenCVParameter = tenCV != null ?
                new ObjectParameter("TenCV", tenCV) :
                new ObjectParameter("TenCV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemChucVu", tenCVParameter);
        }
    
        public virtual int sp_SuaChucVu(string maCV, string tenCV)
        {
            var maCVParameter = maCV != null ?
                new ObjectParameter("MaCV", maCV) :
                new ObjectParameter("MaCV", typeof(string));
    
            var tenCVParameter = tenCV != null ?
                new ObjectParameter("TenCV", tenCV) :
                new ObjectParameter("TenCV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaChucVu", maCVParameter, tenCVParameter);
        }
    
        public virtual int sp_XoaChucVu(string maCV)
        {
            var maCVParameter = maCV != null ?
                new ObjectParameter("MaCV", maCV) :
                new ObjectParameter("MaCV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaChucVu", maCVParameter);
        }
    }
}
